custom_file_path:
  style: source/_data/styles.styl
menu:
  about: /about/ || fa fa-user
  home: / || fa fa-home
  categories: /categories/ || fa fa-th
social:
  GitHub: https://github.com/CloudyAnt|| fab fa-github
  E-Mail: iiim.cloudy@gmail.com || fa fa-envelope
# Schemes
# scheme: Muse
# scheme: Mist
scheme: Pisces
# scheme: Gemini

# Dark Mode
darkmode: true
