custom_file_path:
  # postMeta: source/_data/next-post-meta.njk
  style: source/_data/next-styles.styl
  #head: source/_data/head.njk
  #header: source/_data/header.njk
  #sidebar: source/_data/sidebar.njk
  #postBodyEnd: source/_data/post-body-end.njk
  #footer: source/_data/footer.njk
  #bodyEnd: source/_data/body-end.njk
  #variable: source/_data/variables.styl
  #mixin: source/_data/mixins.sty
menu:
  about: /about/ || fa fa-user
  home: / || fa fa-home
  categories: /categories/ || fa fa-th
social:
  GitHub: https://github.com/CloudyAnt|| fab fa-github
  E-Mail: iiim.cloudy@gmail.com || fa fa-envelope
# Schemes
# scheme: Muse
# scheme: Mist
scheme: Pisces
# scheme: Gemini

# Dark Mode
darkmode: true
